# Nothing is OS-specific, so we're only testing on Linux right now.
# If any OS-specific bugs show up, we can change that. -@duckinator

Lint_task:
  container:
    cpu: 1
    memory: 512Mi
    image: python:3.11-slim
  install_script:
    - pip install -U pip
    - pip install .
    - pip install .[lint] .[test] bork
  script:
    - pylint --version
    - bork run lint

Linux_task:
  alias: Linux tests
  container:
    cpu: 1
    memory: 512Mi
    matrix:
      - image: python:3.8-slim
      - image: python:3.9-slim
      - image: python:3.10-slim
      - image: python:3.11-slim
  install_script:
    - pip install -U pip
    - pip install . .[test] bork
  script:
    - python3 --version
    - bork run test

success_task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - Lint
    - Linux tests

# If homf/version.py is modified on the main branch, make a release.
Release_task:
  only_if: "changesInclude('homf/version.py') && $BRANCH == 'main' && $CIRRUS_CRON == ''"
  depends_on: [CI success]
  env:
    BORK_PYPI_USERNAME: "__token__"
    BORK_PYPI_PASSWORD: ENCRYPTED[99be9b7794bdd10b3d711c2482ab108fb361b8f89242eb813cec4edcd2b714f98b13b652a2123ff5064abd8c6cfed373]
    BORK_GITHUB_TOKEN: ENCRYPTED[e67bc3aec2f14be284e1646e19eb6054ec29046c56f678b636d84771695f6d77cf4766a3dea6c2c3499dbec9eb5e0b02]
  container:
    image: python:3.11-slim
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip install -U pip
    - pip3 install . .[test] bork
  build_script:
    - bork clean
    - bork build
  test_script:
    - bork run test
  release_script:
    - bork release
